# Generated by Django 3.0.7 on 2020-12-25 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alvo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_alvo', models.CharField(help_text='Informe o nome do alvo', max_length=100, verbose_name='Nome do alvo')),
                ('lat', models.CharField(help_text='Latitude', max_length=100, verbose_name='Latitude')),
                ('lon', models.CharField(help_text='Longitude', max_length=100, verbose_name='Longitude')),
                ('data_expiracao', models.DateField(help_text='Informe a data de expiração', max_length=100, verbose_name='Data de expiração')),
            ],
            options={
                'verbose_name': 'Alvo',
                'verbose_name_plural': 'Alvos',
                'ordering': ['-nome_alvo'],
            },
        ),
    ]
